# Generated by Django 4.2.7 on 2023-12-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="transaction_id",
            new_name="order_number",
        ),
    ]
