# Generated by Django 4.2.7 on 2023-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="transaction_id",
            field=models.UUIDField(
                default="8ce30b815df5489ea92bf958d5e4ac6e",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
