# Generated by Django 4.2.7 on 2023-12-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_transaction_id_cart_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_address",
                to="store.billingaddress",
            ),
        ),
    ]
