# Generated by Django 4.2.7 on 2023-12-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_cart_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingaddress",
            options={},
        ),
        migrations.RenameField(
            model_name="billingaddress",
            old_name="is_no_billing_address",
            new_name="is_billing_address",
        ),
    ]
