# Generated by Django 4.2.7 on 2023-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_cart_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="transaction_id",
            field=models.UUIDField(
                default="f063f9a32e86429b8268de9aaaf6644a",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
