# Generated by Django 4.2.7 on 2024-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/default_image.PNG",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
