# Generated by Django 4.2.7 on 2024-06-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storeSellers", "0001_initial"),
        ("store", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storeSellers.seller",
            ),
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
