# Generated by Django 4.2.7 on 2023-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cart_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="transaction_id",
            field=models.UUIDField(
                default="34c5b0ffbf3a4f21892d43e64230cce0",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
