# Generated by Django 4.2.7 on 2023-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_cart_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="transaction_id",
            field=models.UUIDField(
                default="248260ead0df402eade0b9bb7c1e4b27",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
