# Generated by Django 4.2.7 on 2024-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
