# Generated by Django 4.2.7 on 2024-01-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_name", models.CharField(max_length=50)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Please use the format YYYY-MM-DD"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Please use the format YYYY-MM-DD"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="product",
            name="promo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.promotion",
            ),
        ),
    ]
