# Generated by Django 4.2.16 on 2025-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cartitem_status_alter_cart_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('processing', 'Processing'), ('canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
    ]
