# Generated by Django 4.2.7 on 2024-01-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_promotion_alter_product_discount_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.seller",
            ),
        ),
    ]
