# Generated by Django 4.2.7 on 2024-01-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_product_seller_product_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.promotion",
            ),
        ),
    ]
