# Generated by Django 4.2.7 on 2024-01-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_cart_complete_cart_status_sellerorders_return"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SellerOrders",
        ),
    ]
