# Generated by Django 4.2.7 on 2024-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_cart_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(help_text="Please use the format YYYY-MM-DD"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(help_text="Please use the format YYYY-MM-DD"),
        ),
    ]
