# Generated by Django 4.2.7 on 2024-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_remove_product_user_product_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("unconfirmed", "Unconfirmed"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                ],
                default="Unconfirmed",
                max_length=20,
                null=True,
            ),
        ),
    ]
