# Generated by Django 4.2.7 on 2024-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_cart_address_alter_cart_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
