# Generated by Django 4.2.7 on 2024-04-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_cart_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
