# Generated by Django 4.2.7 on 2024-04-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_paymentmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentModel",
        ),
    ]
