# Generated by Django 4.2.7 on 2024-04-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paymentapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmodel",
            old_name="cart",
            new_name="order",
        ),
    ]
