# Generated by Django 4.2.7 on 2024-04-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentapp", "0002_rename_cart_paymentmodel_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="mode_of_payment",
            field=models.CharField(
                choices=[
                    ("flutterwave", "Flutterwave"),
                    ("paystack", "Paystack"),
                    ("remita", "Remita"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
