# Generated by Django 4.2.16 on 2024-12-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='mode_of_payment',
        ),
    ]
