# Generated by Django 4.2.7 on 2024-03-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
