# Generated by Django 4.2.7 on 2024-03-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_password"),
    ]

    operations = []
