# Generated by Django 4.2.7 on 2024-03-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20240319_0203"),
    ]

    operations = []
